# Generated by Django 4.0.4 on 2022-05-29 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('dateOfBirth', models.DateField(default=datetime.date(2022, 5, 29), verbose_name='Дата_рождения')),
                ('dateOfDeath', models.DateField(default='', verbose_name='Дата_смерти')),
                ('placeOfBirth', models.CharField(max_length=100, verbose_name='Место_рождения')),
                ('placeOfDeath', models.CharField(max_length=100, verbose_name='Место_смерти')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('photo', models.ImageField(upload_to='composers/', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композиторы',
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Эпоха')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Эпоха',
                'verbose_name_plural': 'Эпохи',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('dateOfPlay', models.CharField(max_length=100, verbose_name='Дата_исполнения')),
                ('video', models.FileField(upload_to='perfomance/', verbose_name='Видео')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Исполнение',
                'verbose_name_plural': 'Исполнения',
            },
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='pieceOfArt/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicalmusic.reviews', verbose_name='родитель')),
                ('perfomance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classicalmusic.perfomance', verbose_name='исполнение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='PieceOfArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('dateOfWrite', models.CharField(max_length=100, verbose_name='Дата_написания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classicalmusic.composer', verbose_name='композитор')),
                ('genres', models.ManyToManyField(to='classicalmusic.genre', verbose_name='жанры')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.AddField(
            model_name='perfomance',
            name='performers',
            field=models.ManyToManyField(to='classicalmusic.performers', verbose_name='исполнители'),
        ),
        migrations.AddField(
            model_name='perfomance',
            name='pieceOfArt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classicalmusic.pieceofart', verbose_name='произведение'),
        ),
        migrations.AddField(
            model_name='composer',
            name='eras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicalmusic.era', verbose_name='Эпоха'),
        ),
    ]
