# Generated by Django 4.0.4 on 2022-05-30 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicalmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofart',
            name='photo',
            field=models.ImageField(default='top.jpg', upload_to='pieceOfArt/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2022, 5, 30), verbose_name='Дата_рождения'),
        ),
    ]
