# Generated by Django 4.0.4 on 2022-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicalmusic', '0003_alter_perfomance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='country_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='composer',
            name='country_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='composer',
            name='country_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='composer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='composer',
            name='description_kor',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='composer',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='composer',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='composer',
            name='name_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='composer',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfBirth_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_рождения'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfBirth_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_рождения'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfBirth_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_рождения'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfDeath_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_смерти'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfDeath_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_смерти'),
        ),
        migrations.AddField(
            model_name='composer',
            name='placeOfDeath_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Место_смерти'),
        ),
        migrations.AddField(
            model_name='era',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='era',
            name='description_kor',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='era',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='era',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Эпоха'),
        ),
        migrations.AddField(
            model_name='era',
            name='name_kor',
            field=models.CharField(max_length=150, null=True, verbose_name='Эпоха'),
        ),
        migrations.AddField(
            model_name='era',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Эпоха'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_kor',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='performers',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='performers',
            name='description_kor',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='performers',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='performers',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='performers',
            name='name_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='performers',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='description_kor',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='name_kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='pieceofart',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
