# Generated by Django 4.0.4 on 2022-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicalmusic', '0006_composer_country_ko_composer_description_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='wikiurl',
            field=models.CharField(default='', max_length=150, verbose_name='СсылкаВики'),
        ),
    ]
